import type { CivicEvent } from './types';

// City center for the demo — a fictional city layout
const CITY_CENTER = { lat: 26.9124, lng: 75.7873 };

function offset(lat: number, lng: number, dLat: number, dLng: number) {
  return { lat: lat + dLat, lng: lng + dLng };
}

function minutesAgo(min: number): string {
  return new Date(Date.now() - min * 60_000).toISOString();
}

export const SIMULATED_EVENTS: CivicEvent[] = [
  {
    id: 'sim-001',
    source: 'simulated',
    type: 'traffic',
    category: 'Heavy Traffic',
    description: 'Traffic moving slowly near Tonk Road junction. Congestion building up during evening rush.',
    location_text: 'Tonk Road, Near Gaurav Tower',
    latitude: offset(CITY_CENTER.lat, CITY_CENTER.lng, 0.008, 0.012).lat,
    longitude: offset(CITY_CENTER.lat, CITY_CENTER.lng, 0.008, 0.012).lng,
    timestamp: minutesAgo(8),
    severity: 'high',
    photo_url: null,
    verification_status: 'corroborated',
    supporting_count: 5,
  },
  {
    id: 'sim-002',
    source: 'simulated',
    type: 'water',
    category: 'Waterlogging',
    description: 'Water accumulation reported near XYZ Road after sustained rainfall. Road partially impassable.',
    location_text: 'XYZ Road, Near City Mall',
    latitude: offset(CITY_CENTER.lat, CITY_CENTER.lng, -0.006, 0.009).lat,
    longitude: offset(CITY_CENTER.lat, CITY_CENTER.lng, -0.006, 0.009).lng,
    timestamp: minutesAgo(12),
    severity: 'high',
    photo_url: null,
    verification_status: 'corroborated',
    supporting_count: 3,
  },
  {
    id: 'sim-003',
    source: 'simulated',
    type: 'weather',
    category: 'Heavy Rainfall',
    description: 'Heavy rainfall detected in central district. Visibility reduced. Rain intensity increasing.',
    location_text: 'Central District',
    latitude: offset(CITY_CENTER.lat, CITY_CENTER.lng, 0.003, -0.005).lat,
    longitude: offset(CITY_CENTER.lat, CITY_CENTER.lng, 0.003, -0.005).lng,
    timestamp: minutesAgo(5),
    severity: 'high',
    photo_url: null,
    verification_status: 'corroborated',
    supporting_count: 8,
  },
  {
    id: 'sim-004',
    source: 'simulated',
    type: 'traffic',
    category: 'Road Accident',
    description: 'Two-vehicle collision reported on MI Road. Lane blocked. Emergency services on scene.',
    location_text: 'MI Road, Near Statue Circle',
    latitude: offset(CITY_CENTER.lat, CITY_CENTER.lng, 0.005, -0.011).lat,
    longitude: offset(CITY_CENTER.lat, CITY_CENTER.lng, 0.005, -0.011).lng,
    timestamp: minutesAgo(18),
    severity: 'critical',
    photo_url: null,
    verification_status: 'likely_credible',
    supporting_count: 2,
  },
  {
    id: 'sim-005',
    source: 'simulated',
    type: 'complaint',
    category: 'Garbage',
    description: 'Large pile of uncollected garbage near residential area. Overflowing bins reported by multiple residents.',
    location_text: 'Vaishali Nagar, Sector 5',
    latitude: offset(CITY_CENTER.lat, CITY_CENTER.lng, -0.014, -0.008).lat,
    longitude: offset(CITY_CENTER.lat, CITY_CENTER.lng, -0.014, -0.008).lng,
    timestamp: minutesAgo(35),
    severity: 'moderate',
    photo_url: null,
    verification_status: 'needs_verification',
    supporting_count: 1,
  },
  {
    id: 'sim-006',
    source: 'simulated',
    type: 'complaint',
    category: 'Streetlight',
    description: 'Streetlight not working on dark stretch of road near park. Safety concern for pedestrians at night.',
    location_text: 'Central Park, Near Gate 2',
    latitude: offset(CITY_CENTER.lat, CITY_CENTER.lng, -0.003, 0.006).lat,
    longitude: offset(CITY_CENTER.lat, CITY_CENTER.lng, -0.003, 0.006).lng,
    timestamp: minutesAgo(52),
    severity: 'low',
    photo_url: null,
    verification_status: 'needs_verification',
    supporting_count: 1,
  },
  {
    id: 'sim-007',
    source: 'simulated',
    type: 'complaint',
    category: 'Road Damage',
    description: 'Large pothole on main road causing vehicles to swerve. Risk of accidents especially for two-wheelers.',
    location_text: 'Jawahar Circle, Main Road',
    latitude: offset(CITY_CENTER.lat, CITY_CENTER.lng, 0.011, 0.003).lat,
    longitude: offset(CITY_CENTER.lat, CITY_CENTER.lng, 0.011, 0.003).lng,
    timestamp: minutesAgo(67),
    severity: 'moderate',
    photo_url: null,
    verification_status: 'likely_credible',
    supporting_count: 4,
  },
  {
    id: 'sim-008',
    source: 'simulated',
    type: 'weather',
    category: 'Air Quality',
    description: 'AQI at 142 (Unhealthy for Sensitive Groups). Pollution levels elevated in industrial zone.',
    location_text: 'Industrial Area, Phase 2',
    latitude: offset(CITY_CENTER.lat, CITY_CENTER.lng, -0.019, 0.014).lat,
    longitude: offset(CITY_CENTER.lat, CITY_CENTER.lng, -0.019, 0.014).lng,
    timestamp: minutesAgo(15),
    severity: 'moderate',
    photo_url: null,
    verification_status: 'corroborated',
    supporting_count: 6,
  },
  {
    id: 'sim-009',
    source: 'simulated',
    type: 'water',
    category: 'Water Supply',
    description: 'Low water pressure reported in residential colony since morning. Supply disruption expected.',
    location_text: 'Mansarovar, Block C',
    latitude: offset(CITY_CENTER.lat, CITY_CENTER.lng, -0.022, -0.016).lat,
    longitude: offset(CITY_CENTER.lat, CITY_CENTER.lng, -0.022, -0.016).lng,
    timestamp: minutesAgo(90),
    severity: 'moderate',
    photo_url: null,
    verification_status: 'likely_credible',
    supporting_count: 3,
  },
  {
    id: 'sim-010',
    source: 'simulated',
    type: 'noise',
    category: 'Noise Complaint',
    description: 'Construction noise reported outside permitted hours. Ongoing since early morning.',
    location_text: 'Civil Lines, Near Hospital',
    latitude: offset(CITY_CENTER.lat, CITY_CENTER.lng, 0.016, -0.003).lat,
    longitude: offset(CITY_CENTER.lat, CITY_CENTER.lng, 0.016, -0.003).lng,
    timestamp: minutesAgo(40),
    severity: 'low',
    photo_url: null,
    verification_status: 'needs_verification',
    supporting_count: 2,
  },
  {
    id: 'sim-011',
    source: 'simulated',
    type: 'transit',
    category: 'Bus Delay',
    description: 'Route 12 bus delayed by 25 minutes due to traffic congestion on main corridor.',
    location_text: 'Sindhi Camp Bus Stand',
    latitude: offset(CITY_CENTER.lat, CITY_CENTER.lng, 0.007, -0.007).lat,
    longitude: offset(CITY_CENTER.lat, CITY_CENTER.lng, 0.007, -0.007).lng,
    timestamp: minutesAgo(22),
    severity: 'moderate',
    photo_url: null,
    verification_status: 'likely_credible',
    supporting_count: 4,
  },
  {
    id: 'sim-012',
    source: 'simulated',
    type: 'transit',
    category: 'Train Delay',
    description: 'Local train on Pink Line delayed by 15 minutes due to signal failure near central station.',
    location_text: 'Central Railway Station',
    latitude: offset(CITY_CENTER.lat, CITY_CENTER.lng, -0.009, -0.012).lat,
    longitude: offset(CITY_CENTER.lat, CITY_CENTER.lng, -0.009, -0.012).lng,
    timestamp: minutesAgo(30),
    severity: 'moderate',
    photo_url: null,
    verification_status: 'corroborated',
    supporting_count: 7,
  },
  {
    id: 'sim-013',
    source: 'simulated',
    type: 'traffic',
    category: 'Road Blockage',
    description: 'Road blocked due to fallen tree after strong winds. Diversion in place.',
    location_text: 'Bani Park, Main Road',
    latitude: offset(CITY_CENTER.lat, CITY_CENTER.lng, 0.014, 0.008).lat,
    longitude: offset(CITY_CENTER.lat, CITY_CENTER.lng, 0.014, 0.008).lng,
    timestamp: minutesAgo(45),
    severity: 'high',
    photo_url: null,
    verification_status: 'corroborated',
    supporting_count: 3,
  },
  {
    id: 'sim-014',
    source: 'simulated',
    type: 'water',
    category: 'Pipe Leakage',
    description: 'Water pipe leakage causing flooding on service road. Water authority notified.',
    location_text: 'Malviya Nagar, Near Market',
    latitude: offset(CITY_CENTER.lat, CITY_CENTER.lng, -0.011, 0.017).lat,
    longitude: offset(CITY_CENTER.lat, CITY_CENTER.lng, -0.011, 0.017).lng,
    timestamp: minutesAgo(55),
    severity: 'moderate',
    photo_url: null,
    verification_status: 'needs_verification',
    supporting_count: 1,
  },
  {
    id: 'sim-015',
    source: 'simulated',
    type: 'complaint',
    category: 'Damaged Road',
    description: 'Road surface crumbling along a 50-meter stretch. Hazardous for two-wheelers.',
    location_text: 'C-Scheme, Near Tax Office',
    latitude: offset(CITY_CENTER.lat, CITY_CENTER.lng, 0.002, 0.014).lat,
    longitude: offset(CITY_CENTER.lat, CITY_CENTER.lng, 0.002, 0.014).lng,
    timestamp: minutesAgo(72),
    severity: 'moderate',
    photo_url: null,
    verification_status: 'likely_credible',
    supporting_count: 5,
  },
  {
    id: 'sim-016',
    source: 'simulated',
    type: 'weather',
    category: 'Temperature',
    description: 'Current temperature 34°C with high humidity (78%). Feels like 38°C.',
    location_text: 'City Center',
    latitude: CITY_CENTER.lat,
    longitude: CITY_CENTER.lng,
    timestamp: minutesAgo(3),
    severity: 'low',
    photo_url: null,
    verification_status: 'corroborated',
    supporting_count: 1,
  },
  {
    id: 'sim-017',
    source: 'simulated',
    type: 'noise',
    category: 'Noise Complaint',
    description: 'Loud music from event venue past permitted hours. Multiple residents affected.',
    location_text: 'Rambagh, Near Hotel District',
    latitude: offset(CITY_CENTER.lat, CITY_CENTER.lng, -0.005, -0.015).lat,
    longitude: offset(CITY_CENTER.lat, CITY_CENTER.lng, -0.005, -0.015).lng,
    timestamp: minutesAgo(110),
    severity: 'low',
    photo_url: null,
    verification_status: 'conflicting_reports',
    supporting_count: 2,
  },
  {
    id: 'sim-018',
    source: 'simulated',
    type: 'complaint',
    category: 'Pollution',
    description: 'Industrial smoke visible from residential area. Strong odour reported by residents.',
    location_text: 'Shyam Nagar, Near Industrial Border',
    latitude: offset(CITY_CENTER.lat, CITY_CENTER.lng, -0.018, -0.020).lat,
    longitude: offset(CITY_CENTER.lat, CITY_CENTER.lng, -0.018, -0.020).lng,
    timestamp: minutesAgo(28),
    severity: 'moderate',
    photo_url: null,
    verification_status: 'needs_verification',
    supporting_count: 1,
  },
];

export { CITY_CENTER };
